config/routes.rb
Rails.application.routes.draw do

  root to: 'list_documents#index', as: 'list_documents'

  resources :list_documents do
    collection do
      get 'filter'
    end

    member do
      get 'download'
      get 'upload_to_teamlab'
      get 'open_on_testrail'
    end
  end

  resources :list_spreadsheets do
    collection do
      get 'filter'
    end

    member do
      get 'download'
      get 'upload_to_teamlab'
      get 'open_on_testrail'
    end
  end

  resources :list_presentations do
    collection do
      get 'filter'
    end

    member do
      get 'download'
      get 'upload_to_teamlab'
      get 'open_on_testrail'
    end
  end

  get 'list_documents/index'

end

app/models/list_spreadsheet.rb
class ListSpreadsheet
  include Mongoid::Document
  attr_accessor :path
  belongs_to :spreadsheet

  validates :path, format: {
      with: %r{\.(xlsx)\Z}i,
      message: 'Must be path to .xlsx file.'
  }
  attr_reader :attributes
end

app/controllers/list_spreadsheets_controller.rb
require_relative '../../../SharedFunctional/TestrailAPI/API2.0/Testrail'
require 'teamlab'

class ListSpreadsheetsController < ApplicationController
  include ListSpreadsheetsHelper
  before_action :set_list_spreadsheet, only: [:show, :edit, :update, :destroy, :download, :upload_to_teamlab, :open_on_testrail]
  before_action :authenticate_to_teamlab, only: [:upload_to_teamlab]

  # GET /list_spreadsheets
  # GET /list_spreadsheets.json
  def index
    @list_spreadsheets = ListSpreadsheet.all.to_a
  end

  # GET /list_spreadsheets/1
  # GET /list_spreadsheets/1.json
  def show
    @spreadsheet = ListSpreadsheet.find(params[:id]).spreadsheet['structure']
    respond_to do |format|
      format.html
      format.xml { render xml: @spreadsheet }
    end
  end

  # GET /list_spreadsheets/new
  def new
    @list_spreadsheet = ListSpreadsheet.new
  end

  # GET /list_spreadsheets/1/edit
  def edit
  end

  # POST /list_spreadsheets
  # POST /list_spreadsheets.json
  def create
    @list_spreadsheet = ListSpreadsheet.new(list_spreadsheet_params)

    respond_to do |format|
      if @list_spreadsheet.save
        format.html { redirect_to @list_spreadsheet, notice: 'List spreadsheet was successfully created.' }
        format.json { render :show, status: :created, location: @list_spreadsheet }
      else
        format.html { render :new }
        format.json { render json: @list_spreadsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_spreadsheets/1
  # PATCH/PUT /list_spreadsheets/1.json
  def update
    respond_to do |format|
      if @list_spreadsheet.update(list_spreadsheet_params)
        format.html { redirect_to @list_spreadsheet, notice: 'List spreadsheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_spreadsheet }
      else
        format.html { render :edit }
        format.json { render json: @list_spreadsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_spreadsheets/1
  # DELETE /list_spreadsheets/1.json
  def destroy
    @list_spreadsheet.destroy
    respond_to do |format|
      format.html { redirect_to list_spreadsheets_url, notice: 'List spreadsheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    send_file @list_spreadsheet.attributes['path'], :type=>"application/xml", :x_sendfile=>true
  end

  def upload_to_teamlab
    file_id = Teamlab.files.upload_to_my_docs(@list_spreadsheet.attributes['path']).body['response']['id']
    respond_to do |format|
      format.html { redirect_to Teamlab.files.generate_shared_link(file_id, 'ReadWrite').body['response']}
    end
  end

  def filter
    @list_spreadsheets ||= filter_spreadsheets(params)
    respond_to do |format|
      format.js
    end
  end

  def open_on_testrail
    case_id = Testrail2.new.project(68).suite(39834).section(58251).case(@list_spreadsheet.attributes['path']).id
    respond_to do |format|
      format.html { redirect_to "http://tm-testrail.no-ip.org/testrail/index.php?/cases/results/#{case_id}"}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_spreadsheet
      @list_spreadsheet = ListSpreadsheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_spreadsheet_params
      params[:list_spreadsheet]
    end

    def authenticate_to_teamlab
      Teamlab.configure do |config|
        config.server = TEAMLAB[:server]
        config.username = TEAMLAB[:username]
        config.password = TEAMLAB[:password]
      end
    end
end

app/helpers/list_spreadsheets_helper.rb
module ListSpreadsheetsHelper
  TAGS = %w(worksheet merged_cell hyperlink image shape group_shape chart column formula autofilter formatted_table hidden_row comment frozen_range)
  TEAMLAB = {server: 'https://testinfo.teamlab.info', username: 'alexeysemin88@gmail.com', password: '123456'}

  def filter_spreadsheets(params)
    @list_presentations = ListSpreadsheet.all.to_a
    parse_parameters(params)
    return @list_presentations if @parsed_params.empty?
    @list_presentations.select! { |list_spreadsheet| compare_spreadsheet(list_spreadsheet) }
  end

  private

  def parse_parameters(params)
    @parsed_params = {}
    TAGS.each do |element|
      if params["#{element}_checkbox".to_sym].to_i == 1
        @parsed_params["#{element}s".to_sym] = {from: params["#{element}s_from"].to_i}
        @parsed_params["#{element}s".to_sym][:to] = params["#{element}s_to"].to_i if correct_value?(params["#{element}s_to"])
      end
    end
  end

  def compare_spreadsheet(list_spreadsheet)
    result = true
    @parsed_params.each do |key, value|
      list_spreadsheet_value = list_spreadsheet.attributes['tags'][key]
      result &&= list_spreadsheet_value >= value[:from] && (value.has_key?(:to) ? (list_spreadsheet_value <= value[:to]) : true)
    end
    puts result
    result
  end

  def correct_value?(param)
    param != '' && param
  end
end

app/views/list_spreadsheets/_form.html.erb
<%= form_for(@list_spreadsheet) do |f| %>
  <% if @list_spreadsheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_spreadsheet.errors.count, "error") %> prohibited this list_spreadsheet from being saved:</h2>

      <ul>
      <% @list_spreadsheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_spreadsheets/_list_spreadsheet.erb
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  <td>
    <%= link_to image_tag('xlsx.png', class: 'listItemImage'), download_list_spreadsheet_path(list_spreadsheet), title: 'Download spreadsheet', rel: 'tooltip', target: '_blank' %>
    <%= link_to image_tag('TM_logo.png', class: 'listItemImage'), upload_to_teamlab_list_spreadsheet_path(list_spreadsheet), title: 'Upload to TeamLab.info', rel: 'tooltip', target: '_blank' %>
    <%= link_to image_tag('testrail.png', class: 'listItemImage'), open_on_testrail_list_spreadsheet_path(list_spreadsheet), title: 'Open Testrail results', rel: 'tooltip', target: '_blank' %>
  </td>
  <td>
    <p><%= link_to list_spreadsheet.attributes[:path], list_spreadsheet %></p>
  </td>
  <td>
    <ul>
      <li>Листов: <%= list_spreadsheet.attributes['tags']['worksheets'] %></li>
      <li>Объединенных ячеек: <%= list_spreadsheet.attributes['tags']['merged_cells'] %></li>
      <li>Ссылок: <%= list_spreadsheet.attributes['tags']['hyperlinks'] %></li>
      <li>Картинок: <%= list_spreadsheet.attributes['tags']['images'] %></li>
      <li>Автофигур: <%= list_spreadsheet.attributes['tags']['shapes'] %></li>
      <li>Диаграмм: <%= list_spreadsheet.attributes['tags']['charts'] %></li>
      <li>Группированых автофигур: <%= list_spreadsheet.attributes['tags']['group_shapes'] %></li>
      <li>Колонок: <%= list_spreadsheet.attributes['tags']['columns'] %></li>
      <li>Автофильтров: <%= list_spreadsheet.attributes['tags']['autofilters'] %></li>
      <li>Форматированных таблиц: <%= list_spreadsheet.attributes['tags']['formatted_tables'] %></li>
      <li>Скрытых строк: <%= list_spreadsheet.attributes['tags']['hidden_rows'] %></li>
      <li>Комментариев: <%= list_spreadsheet.attributes['tags']['comments'] %></li>
      <li>Формул: <%= list_spreadsheet.attributes['tags']['formulas'] %></li>
      <li>Закрепенных областей: <%= list_spreadsheet.attributes['tags']['frozen_ranges'] %></li>
    </ul>
  </td>
</tr>

app/views/list_spreadsheets/edit.html.erb
<h1>Editing list_spreadsheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_spreadsheet %> |
<%= link_to 'Back', list_spreadsheets_path %>

app/views/list_spreadsheets/filter.js.erb
/**
 * Created by zagudaev-2 on 6/24/14.
 */
$('#listSpreadsheets').html('<%= escape_javascript render(@list_presentations) %>');

app/views/list_spreadsheets/index.html.erb
<div class="tabs">
  <ul class="tab-links">
    <li><%= link_to 'Documents', list_documents_path %></li>
    <li><%= link_to 'Spreadsheets', list_spreadsheets_path %></li>
    <li><%= link_to 'Presentations', list_presentations_path %></li>
  </ul>
</div>
<h1>Spreadsheets list</h1>

<%= form_tag(filter_list_spreadsheets_path, method: 'get', remote: true) do %>
    <% ListSpreadsheetsHelper::TAGS.each do |tag_name| %>
        <div>
          <%= check_box_tag "#{tag_name}_checkbox".to_sym, 1, false, onclick: "$(\"##{tag_name}Properties\")[this.checked ? 'show' : 'hide']();" %>
          <%= label_tag("#{tag_name}_checkbox", "Include #{tag_name}s?") %>
          <div id="<%=tag_name%>Properties" style="display: none;">
            <ul>
              <li><%= label_tag("#{tag_name}s_from", 'от', class: 'labelForParameter') %>
                <div><%= text_field_tag("#{tag_name}s_from", 1, class: 'textFieldParameter') %></div></li>
              <li><%= label_tag("#{tag_name}s_to", 'до', class: 'labelForParameter') %>
                <div><%= text_field_tag("#{tag_name}s_to", nil, class: 'textFieldParameter') %></div></li>
            </ul>
          </div>
        </div>
    <% end %>
    <div id="btnSubmit">
      <%= submit_tag 'Filter!' %>
    </div>
<% end %>
<table>
  <tr>
    <th>Download</th>
    <th>Path to spreadsheet</th>
    <th>Tags</th>
  </tr>
  <tbody id="listSpreadsheets">
  <%= render @list_spreadsheets %>
  </tbody>
</table>

<br>

app/views/list_spreadsheets/new.html.erb
<h1>New list_spreadsheet</h1>

<%= render 'form' %>

<%= link_to 'Back', list_spreadsheets_path %>

app/views/list_spreadsheets/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', list_spreadsheets_path %>
<p><%= @spreadsheet %></p>