config/routes.rb
Rails.application.routes.draw do

  root to: 'list_documents#index', as: 'list_documents'

  resources :list_documents do
    collection do
      get 'filter'
    end

    member do
      get 'download'
      get 'upload_to_teamlab'
      get 'open_on_testrail'
    end
  end

  resources :list_spreadsheets do
    collection do
      get 'filter'
    end

    member do
      get 'download'
      get 'upload_to_teamlab'
      get 'open_on_testrail'
    end
  end

  resources :list_presentations do
    collection do
      get 'filter'
    end

    member do
      get 'download'
      get 'upload_to_teamlab'
      get 'open_on_testrail'
    end
  end

  get 'list_documents/index'

end

app/models/list_presentation.rb
class ListPresentation
  include Mongoid::Document
  attr_accessor :path
  belongs_to :presentation

  validates :path, format: {
      with: %r{\.(pptx)\Z}i,
      message: 'Must be path to .pptx file.'
  }
  attr_reader :attributes
end

app/controllers/list_presentations_controller.rb
class ListPresentationsController < ApplicationController
  include ListPresentationsHelper

  before_action :set_list_presentation, only: [:show, :edit, :update, :destroy, :download, :upload_to_teamlab, :open_on_testrail]
  before_action :authenticate_to_teamlab, only: [:upload_to_teamlab]

  # GET /list_presentations
  # GET /list_presentations.json
  def index
    @list_presentations = ListPresentation.all
  end

  # GET /list_presentations/1
  # GET /list_presentations/1.json
  def show
    @presentation = ListPresentation.find(params[:id]).presentation['structure']
    respond_to do |format|
      format.html
      format.xml { render xml: @presentation }
    end
  end

  # GET /list_presentations/new
  def new
    @list_presentation = ListPresentation.new
  end

  # GET /list_presentations/1/edit
  def edit
  end

  # POST /list_presentations
  # POST /list_presentations.json
  def create
    @list_presentation = ListPresentation.new(list_presentation_params)

    respond_to do |format|
      if @list_presentation.save
        format.html { redirect_to @list_presentation, notice: 'List presentation was successfully created.' }
        format.json { render :show, status: :created, location: @list_presentation }
      else
        format.html { render :new }
        format.json { render json: @list_presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_presentations/1
  # PATCH/PUT /list_presentations/1.json
  def update
    respond_to do |format|
      if @list_presentation.update(list_presentation_params)
        format.html { redirect_to @list_presentation, notice: 'List presentation was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_presentation }
      else
        format.html { render :edit }
        format.json { render json: @list_presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_presentations/1
  # DELETE /list_presentations/1.json
  def destroy
    @list_presentation.destroy
    respond_to do |format|
      format.html { redirect_to list_presentations_url, notice: 'List presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    send_file @list_presentation.attributes['path'], :type=>"application/xml", :x_sendfile=>true
  end

  def upload_to_teamlab
    file_id = Teamlab.files.upload_to_my_docs(@list_presentation.attributes['path']).body['response']['id']
    respond_to do |format|
      format.html { redirect_to Teamlab.files.generate_shared_link(file_id, 'ReadWrite').body['response']}
    end
  end

  def filter
    @list_presentations ||= filter_presentations(params)
    respond_to do |format|
      format.js
    end
  end

  def open_on_testrail
    case_id = Testrail2.new.project(68).suite(16981).section(35127).case(@list_presentation.attributes['path']).id
    respond_to do |format|
      format.html { redirect_to "http://tm-testrail.no-ip.org/testrail/index.php?/cases/results/#{case_id}"}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_presentation
      @list_presentation = ListPresentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_presentation_params
      params[:list_presentation]
    end

  def authenticate_to_teamlab
    Teamlab.configure do |config|
      config.server = TEAMLAB[:server]
      config.username = TEAMLAB[:username]
      config.password = TEAMLAB[:password]
    end
  end
end

app/helpers/list_presentations_helper.rb
require_relative '../../../SharedFunctional/TestrailAPI/API2.0/Testrail'
require 'teamlab'

module ListPresentationsHelper
  TAGS = %w(slide image shape group_shape chart table transition animation hyperlink media formula)
  TEAMLAB = {server: 'https://testinfo.teamlab.info', username: 'alexeysemin88@gmail.com', password: '123456'}

  def filter_presentations(params)
    @list_presentations = ListPresentation.all.to_a
    parse_parameters(params)
    return @list_presentations if @parsed_params.empty?
    @list_presentations.select! { |list_spreadsheet| compare_spreadsheet(list_spreadsheet) }
  end

  private

  def parse_parameters(params)
    @parsed_params = {}
    TAGS.each do |element|
      if params["#{element}_checkbox".to_sym].to_i == 1
        @parsed_params["#{element}s".to_sym] = {from: params["#{element}s_from"].to_i}
        @parsed_params["#{element}s".to_sym][:to] = params["#{element}s_to"].to_i if correct_value?(params["#{element}s_to"])
      end
    end
  end

  def compare_spreadsheet(list_spreadsheet)
    result = true
    @parsed_params.each do |key, value|
      list_presentation_value = list_spreadsheet.attributes['tags'][key]
      result &&= list_presentation_value >= value[:from] && (value.has_key?(:to) ? (list_presentation_value <= value[:to]) : true)
    end
    puts result
    result
  end

  def correct_value?(param)
    param != '' && param
  end
end

app/views/list_presentations/_form.html.erb
<%= form_for(@list_presentation) do |f| %>
  <% if @list_presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_presentation.errors.count, "error") %> prohibited this list_presentation from being saved:</h2>

      <ul>
      <% @list_presentation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_presentations/_list_presentation.erb
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  <td>
    <%= link_to image_tag('pptx.png', class: 'listItemImage'), download_list_presentation_path(list_presentation), title: 'Download presentation', rel: 'tooltip', target: '_blank' %>
    <%= link_to image_tag('TM_logo.png', class: 'listItemImage'), upload_to_teamlab_list_presentation_path(list_presentation), title: 'Upload to TeamLab.info', rel: 'tooltip', target: '_blank' %>
    <%= link_to image_tag('testrail.png', class: 'listItemImage'), open_on_testrail_list_presentation_path(list_presentation), title: 'Open Testrail results', rel: 'tooltip', target: '_blank' %>
  </td>
  <td>
    <p><%= link_to list_presentation.attributes[:path], list_presentation %></p>
  </td>
  <td>
    <ul>
      <li>Слайдов: <%= list_presentation.attributes['tags']['slides'] %></li>
      <li>Ссылок: <%= list_presentation.attributes['tags']['hyperlinks'] %></li>
      <li>Картинок: <%= list_presentation.attributes['tags']['images'] %></li>
      <li>Автофигур: <%= list_presentation.attributes['tags']['shapes'] %></li>
      <li>Диаграмм: <%= list_presentation.attributes['tags']['charts'] %></li>
      <li>Таблиц: <%= list_presentation.attributes['tags']['tables'] %></li>
      <li>Группированых автофигур: <%= list_presentation.attributes['tags']['group_shapes'] %></li>
      <li>Формул: <%= list_presentation.attributes['tags']['formulas'] %></li>
      <li>Аудио/Видео: <%= list_presentation.attributes['tags']['medias'] %></li>
      <li>Эффекты перехода: <%= list_presentation.attributes['tags']['transitions'] %></li>
      <li>Анимация: <%= list_presentation.attributes['tags']['animations'] %></li>
    </ul>
  </td>
</tr>

app/views/list_presentations/edit.html.erb
<h1>Editing list_presentation</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_presentation %> |
<%= link_to 'Back', list_presentations_path %>

app/views/list_presentations/filter.js.erb
/**
 * Created by zagudaev-2 on 6/24/14.
 */
$('#listPresentations').html('<%= escape_javascript render(@list_presentations) %>');

app/views/list_presentations/index.html.erb
<div class="tabs">
  <ul class="tab-links">
    <li><%= link_to 'Documents', list_documents_path %></li>
    <li><%= link_to 'Spreadsheets', list_spreadsheets_path %></li>
    <li><%= link_to 'Presentations', list_presentations_path %></li>
  </ul>
</div>
<h1>Presentations list</h1>

<%= form_tag(filter_list_presentations_path, method: 'get', remote: true) do %>
    <% ListPresentationsHelper::TAGS.each do |tag_name| %>
        <div>
          <%= check_box_tag "#{tag_name}_checkbox".to_sym, 1, false, onclick: "$(\"##{tag_name}Properties\")[this.checked ? 'show' : 'hide']();" %>
          <%= label_tag("#{tag_name}_checkbox", "Include #{tag_name}s?") %>
          <div id="<%=tag_name%>Properties" style="display: none;">
            <ul>
              <li><%= label_tag("#{tag_name}s_from", 'от', class: 'labelForParameter') %>
                <div><%= text_field_tag("#{tag_name}s_from", 1, class: 'textFieldParameter') %></div></li>
              <li><%= label_tag("#{tag_name}s_to", 'до', class: 'labelForParameter') %>
                <div><%= text_field_tag("#{tag_name}s_to", nil, class: 'textFieldParameter') %></div></li>
            </ul>
          </div>
        </div>
    <% end %>
    <div id="btnSubmit">
      <%= submit_tag 'Filter!' %>
    </div>
<% end %>
<table>
  <tr>
    <th>Download</th>
    <th>Path to presentation</th>
    <th>Tags</th>
  </tr>
  <tbody id="listPresentations">
  <%= render @list_presentations %>
  </tbody>
</table>

<br>

app/views/list_presentations/new.html.erb
<h1>New list_presentation</h1>

<%= render 'form' %>

<%= link_to 'Back', list_presentations_path %>

app/views/list_presentations/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', list_presentations_path %>
<p><%= @presentation %></p>