config/routes.rb
Rails.application.routes.draw do

  root to: 'list_documents#index', as: 'list_documents'

  resources :list_documents do
    collection do
      get 'filter'
    end

    member do
      get 'download'
      get 'upload_to_teamlab'
      get 'open_on_testrail'
    end
  end

  resources :list_spreadsheets do
    collection do
      get 'filter'
    end

    member do
      get 'download'
      get 'upload_to_teamlab'
      get 'open_on_testrail'
    end
  end

  resources :list_presentations do
    collection do
      get 'filter'
    end

    member do
      get 'download'
      get 'upload_to_teamlab'
      get 'open_on_testrail'
    end
  end

  get 'list_documents/index'

end

app/models/list_document.rb
class ListDocument
  include Mongoid::Document
  attr_accessor :path
  belongs_to :document

  validates :path, format: {
      with: %r{\.(docx)\Z}i,
      message: 'Must be path to .docx file.'
  }
  attr_reader :attributes
end

app/controllers/list_documents_controller.rb
require_relative '../../../SharedFunctional/TestrailAPI/API2.0/Testrail'
require 'teamlab'
require 'rexml/document'

class ListDocumentsController < ApplicationController
  include ListDocumentsHelper
  before_action :set_list_document, only: [:show, :edit, :update, :destroy, :download, :upload_to_teamlab, :open_on_testrail]
  before_action :authenticate_to_teamlab, only: [:upload_to_teamlab]

  # GET /list_documents
  # GET /list_documents.json
  def index
    @list_documents ||= ListDocument.all.to_a
  end

  # GET /list_documents/1
  # GET /list_documents/1.json
  def show
    @document = ListDocument.find(params[:id]).document['structure']
    respond_to do |format|
      format.html
      format.xml { render xml: @document }
    end
  end

  # GET /list_documents/new
  def new
    @list_document = ListDocument.new
  end

  # GET /list_documents/1/edit
  def edit
  end

  # POST /list_documents
  # POST /list_documents.json
  def create
    @list_document = ListDocument.new(list_document_params)

    respond_to do |format|
      if @list_document.save
        format.html { redirect_to @list_document, notice: 'List document was successfully created.' }
        format.json { render :show, status: :created, location: @list_document }
      else
        format.html { render :new }
        format.json { render json: @list_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_documents/1
  # PATCH/PUT /list_documents/1.json
  def update
    respond_to do |format|
      if @list_document.update(list_document_params)
        format.html { redirect_to @list_document, notice: 'List document was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_document }
      else
        format.html { render :edit }
        format.json { render json: @list_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_documents/1
  # DELETE /list_documents/1.json
  def destroy
    @list_document.destroy
    respond_to do |format|
      format.html { redirect_to list_documents_url, notice: 'List document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    send_file @list_document.attributes['path'], :type=>"application/xml", :x_sendfile=>true
  end

  def upload_to_teamlab
    file_id = Teamlab.files.upload_to_my_docs(@list_document.attributes['path']).body['response']['id']
    respond_to do |format|
      format.html { redirect_to Teamlab.files.generate_shared_link(file_id, 'ReadWrite').body['response']}
    end
  end

  def filter
    @list_documents ||= filter_documents(params)
    respond_to do |format|
      format.js
    end
  end

  def open_on_testrail
    case_id = Testrail2.new.project(68).suite(16976).section(35122).case(@list_document.attributes['path']).id
    respond_to do |format|
      format.html { redirect_to "http://tm-testrail.no-ip.org/testrail/index.php?/cases/results/#{case_id}"}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_document
      @list_document = ListDocument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_document_params
      params[:list_document]
    end

    def authenticate_to_teamlab
      Teamlab.configure do |config|
        config.server = TEAMLAB[:server]
        config.username = TEAMLAB[:username]
        config.password = TEAMLAB[:password]
      end
    end
end

app/helpers/list_documents_helper.rb
module ListDocumentsHelper
  TAGS = %w(paragraph table image shape chart group_shape column section formula)
  TEAMLAB = {server: 'https://testinfo.teamlab.info', username: 'alexeysemin88@gmail.com', password: '123456'}

  def filter_documents(params)
    @list_documents = ListDocument.all.to_a
    parse_parameters(params)
    return @list_documents if @parsed_params.empty?
    @list_documents.select! { |list_document| compare_document(list_document) }
  end

  private

  def parse_parameters(params)
    @parsed_params = {}
    TAGS.each do |element|
      if params["#{element}_checkbox".to_sym].to_i == 1
        @parsed_params["#{element}s".to_sym] = {from: params["#{element}s_from"].to_i}
        @parsed_params["#{element}s".to_sym][:to] = params["#{element}s_to"].to_i if correct_value?(params["#{element}s_to"])
      end
    end
  end

  def compare_document(list_document)
    result = true
    @parsed_params.each do |key, value|
      list_document_value = list_document.attributes['tags'][key]
      result &&= list_document_value >= value[:from] && (value.has_key?(:to) ? (list_document_value <= value[:to]) : true)
    end
    result
  end

  def correct_value?(param)
    param != '' && param
  end
end

app/views/list_documents/_form.html.erb
<%= form_for(@list_document) do |f| %>
    <% if @list_document.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@list_document.errors.count, "error") %> prohibited this list_document from being
            saved:</h2>

          <ul>
            <% @list_document.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :path %>
      <br>
      <%= f.text_field :path, size: 50 %>
    </div>
    <div class="actions">
      <%= f.submit('Add document') %>
    </div>
<% end %>

app/views/list_documents/_list_document.erb
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  <td>
    <%= link_to image_tag('docx.png', class: 'listItemImage'), download_list_document_path(list_document), title: 'Download document', rel: 'tooltip', target: '_blank' %>
    <%= link_to image_tag('TM_logo.png', class: 'listItemImage'), upload_to_teamlab_list_document_path(list_document), title: 'Upload to TeamLab.info', rel: 'tooltip', target: '_blank' %>
    <%= link_to image_tag('testrail.png', class: 'listItemImage'), open_on_testrail_list_document_path(list_document), title: 'Open Testrail results', rel: 'tooltip', target: '_blank' %>
  </td>
  <td>
    <p><%= link_to list_document.attributes[:path], list_document %></p>
  </td>
  <td>
    <ul>
      <li>Параграфов: <%= list_document.attributes['tags']['paragraphs'] %></li>
      <li>Таблиц: <%= list_document.attributes['tags']['tables'] %></li>
      <li>Картинок: <%= list_document.attributes['tags']['images'] %></li>
      <li>Автофигур: <%= list_document.attributes['tags']['shapes'] %></li>
      <li>Диаграмм: <%= list_document.attributes['tags']['charts'] %></li>
      <li>Группированых автофигур: <%= list_document.attributes['tags']['group_shapes'] %></li>
      <li>Колонок: <%= list_document.attributes['tags']['columns'] %></li>
      <li>Секций: <%= list_document.attributes['tags']['sections'] %></li>
      <li>Формул: <%= list_document.attributes['tags']['formulas'] %></li>
    </ul>
  </td>
</tr>

app/views/list_documents/edit.html.erb
<h1>Editing list_document</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_document %> |
<%= link_to 'Back', list_documents_path %>

app/views/list_documents/filter.js.erb
/**
 * Created by zagudaev-2 on 6/24/14.
 */
$('#listDocuments').html('<%= escape_javascript render(@list_documents) %>');

app/views/list_documents/index.html.erb
<div class="tabs">
  <ul class="tab-links">
    <li><%= link_to 'Documents', list_documents_path %></li>
    <li><%= link_to 'Spreadsheets', list_spreadsheets_path %></li>
    <li><%= link_to 'Presentations', list_presentations_path %></li>
  </ul>
</div>
<h1>Documents list</h1>

<%= form_tag(filter_list_documents_path, method: 'get', remote: true) do %>
    <% ListDocumentsHelper::TAGS.each do |tag_name| %>
        <div>
            <%= check_box_tag "#{tag_name}_checkbox".to_sym, 1, false, onclick: "$(\"##{tag_name}Properties\")[this.checked ? 'show' : 'hide']();" %>
            <%= label_tag("#{tag_name}_checkbox", "Include #{tag_name}s?") %>
            <div id="<%=tag_name%>Properties" style="display: none;">
              <ul>
                <li><%= label_tag("#{tag_name}s_from", 'от', class: 'labelForParameter') %>
                  <div><%= text_field_tag("#{tag_name}s_from", 1, class: 'textFieldParameter') %></div></li>
                <li><%= label_tag("#{tag_name}s_to", 'до', class: 'labelForParameter') %>
                  <div><%= text_field_tag("#{tag_name}s_to", nil, class: 'textFieldParameter') %></div></li>
              </ul>
            </div>
        </div>
    <% end %>
    <div id="btnSubmit">
      <%= submit_tag 'Filter!' %>
    </div>
<% end %>
<table>
  <tr>
    <th>Download</th>
    <th>Path to document</th>
    <th>Tags</th>
  </tr>
  <tbody id="listDocuments">
    <%= render @list_documents %>
  </tbody>
</table>

<br>

app/views/list_documents/new.html.erb
<h1>Add document</h1>

<%= render 'form' %>

<%= link_to 'Back', list_documents_path %>

app/views/list_documents/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', list_documents_path %>
<p><%= @document %></p>